### ISSUE TITLE
白名單列表不生效

### ISSUE THREAD

**Issue by Rakau** [Nep-Timeline/Cirno#3]
默認白名單裏有微信，但是在Monitor裏查看還是被凍結了。然後第三方輸入法沒有彈出來，我猜也被凍結了。我嘗試把輸入法包名填進去，重啓后還是不生效

**Comment by Nep-Timeline** [comment]
你的系统是什么？

**Comment by Nep-Timeline** [comment]
HyperOS自带有个墓碑 你可能需要使用
https://shrairo.xyz/d/Onedrive/Public/%E9%99%84%E5%8A%A0%E6%A8%A1%E5%9D%97/%E5%A2%93%E7%A2%91%E9%99%84%E5%8A%A0%E6%A8%A1%E5%9D%97.zip?sign=ntuYGGNBXQXrf0VekdrHZG8YZ2w9OHSxRUep30nP7g8=:0
来禁用它

**Comment by Nep-Timeline** [comment]
微信白名单格式错误的问题已在 4c9fb29 中修复

**Comment by highFreqSurfer** [comment]
我发现在shell用root权限改配置文件会导致own从system变成root，然后读取配置文件失败
