### ISSUE TITLE
The keyboard does not work

### ISSUE THREAD

**Issue by Mahantor** [Nep-Timeline/Cirno#4]
thank you
It is a very good project, please continue to develop it
My keyboard app closes and cannot be run
Is there a way to prevent it from being forced to close?
I use heliboard keyboard
https://github.com/Helium314/HeliBoard

**Comment by Nep-Timeline** [comment]
Add it to the white list

**Comment by Mahantor** [comment]
wchich file must be edit?

**Comment by Nep-Timeline** [comment]
> wchich file must be edit?

data/system/Cirno/applicationSettings.json

**Comment by Mahantor** [comment]
I whitelisted my keyboard, but when I save the file and reset the phone, the file resets again.
What is the cause?
