### ISSUE TITLE
Issue with rest ApplicationSettings

### ISSUE THREAD

**Issue by Mahantor** [Nep-Timeline/Cirno#5]
I whitelisted my keyboard, but when I save the file and reset the phone, the file resets again.
What is the cause?

**Comment by Mahantor** [comment]
Xiaomi redmi note 9 pro
Android 12 orginal
Miui 14 v14.0.3
App version : baka

**Comment by Nep-Timeline** [comment]
Format error

**Comment by Mahantor** [comment]
what do you mean I don't understand
What is the correct format?
I edit the file like this:
[ApplicationSettings.json](https://github.com/user-attachments/files/17119329/ApplicationSettings.json)
